// /frontend/src/components/marketing/TermsOfServicePage.tsx
import React from 'react';

const TermsOfServicePage: React.FC = () => {
  return (
    <div className="bg-white py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-extrabold text-gray-900 mb-8">Terms of Service</h1>
        
        <div className="prose prose-blue prose-lg">
          <p className="text-gray-500">Last updated: May 13, 2025</p>
          
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using the Pix2Code service, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.
          </p>
          
          <h2>2. Description of Service</h2>
          <p>
            Pix2Code is a service that converts screenshots, mockups, and designs into code using artificial intelligence. We provide this service on a subscription basis, with various plans available.
          </p>
          
          <h2>3. User Accounts</h2>
          <p>
            To use Pix2Code, you must create an account. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account.
          </p>
          
          <h2>4. Subscription and Billing</h2>
          <p>
            By subscribing to Pix2Code, you agree to pay the subscription fees according to your selected plan. We use Stripe for payment processing. Subscriptions automatically renew unless canceled at least 24 hours before the renewal date.
          </p>
          
          <h2>5. Credits</h2>
          <p>
            Our service operates on a credit system. Each credit allows for one conversion from design to code. Credits are replenished monthly according to your subscription plan and do not roll over to the next billing period.
          </p>
          
          <h2>6. Acceptable Use</h2>
          <p>
            You agree not to use Pix2Code for any illegal or unauthorized purpose. You must not attempt to disrupt or overwhelm our service or servers.
          </p>
          
          <h2>7. Intellectual Property</h2>
          <p>
            You retain all rights to the designs you upload to Pix2Code. The code generated by our service is owned by you. However, Pix2Code retains all rights to our service, including our AI technology and algorithms.
          </p>
          
          <h2>8. Privacy</h2>
          <p>
            Our Privacy Policy explains how we collect, use, and protect your information. By using Pix2Code, you agree to our collection and use of information as described in our Privacy Policy.
          </p>
          
          <h2>9. Limitation of Liability</h2>
          <p>
            Pix2Code provides the service "as is" without warranties of any kind. We are not responsible for any damages that may result from your use of the service.
          </p>
          
          <h2>10. Changes to Terms</h2>
          <p>
            We may modify these terms at any time. If we make material changes, we will notify you through the service or via email. Your continued use of Pix2Code after such modifications constitutes your acceptance of the updated terms.
          </p>
          
          <h2>11. Termination</h2>
          <p>
            We reserve the right to terminate or suspend your account at our discretion, without notice, for conduct that we believe violates these terms or is harmful to other users, us, or third parties.
          </p>
          
          <h2>12. Governing Law</h2>
          <p>
            These terms shall be governed by the laws of the State of California, without regard to its conflict of law provisions.
          </p>
          
          <h2>13. Contact</h2>
          <p>
            If you have any questions about these Terms of Service, please contact us at legal@pix2code.com.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfServicePage;